# Generated by Django 5.2.12 on 2026-03-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='anomalies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='document',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
